
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'k\xd2\xb2\x0e\xc0\xcf#I\x99coX+y\x92\x93'
    
_lr_action_items = {'LPARAN':([0,1,2,3,4,5,7,8,9,10,12,14,15,17,18,19,20,21,],[1,1,-6,-7,1,1,1,16,-3,-6,1,-8,-4,1,-11,-5,-10,-9,]),'NAME':([0,1,2,3,4,5,7,9,10,12,14,15,17,18,19,20,21,],[2,10,-6,-7,2,10,10,-3,-6,10,-8,-4,10,-11,-5,-10,-9,]),'INT':([0,1,2,3,4,5,7,9,10,12,14,15,17,18,19,20,21,],[3,3,-6,-7,3,3,3,-3,-6,3,-8,-4,3,-11,-5,-10,-9,]),'ASSIGNMENT':([2,],[12,]),'RPARAN':([3,10,11,14,16,18,20,21,],[-7,-6,18,-8,20,-11,-10,-9,]),'PRINT':([0,2,3,4,9,10,14,15,18,19,20,21,],[7,-6,-7,7,-3,-6,-8,-4,-11,-5,-10,-9,]),'PLUS':([2,3,9,10,11,14,15,18,19,20,21,],[-6,-7,17,-6,17,17,17,-11,17,-10,-9,]),'NEGATE':([0,1,2,3,4,5,7,9,10,12,14,15,17,18,19,20,21,],[5,5,-6,-7,5,5,5,-3,-6,5,-8,-4,5,-11,-5,-10,-9,]),'INPUT':([0,1,2,3,4,5,7,9,10,12,14,15,17,18,19,20,21,],[8,8,-6,-7,8,8,8,-3,-6,8,-8,-4,8,-11,-5,-10,-9,]),'$end':([2,3,4,6,9,10,13,14,15,18,19,20,21,],[-6,-7,-1,0,-3,-6,-2,-8,-4,-11,-5,-10,-9,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,1,4,5,7,12,17,],[9,11,9,14,15,19,21,]),'simple_statement':([0,4,],[4,4,]),'simple_statements':([0,4,],[6,13,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> simple_statements","S'",1,None,None,None),
  ('simple_statements -> simple_statement','simple_statements',1,'p_statement_recursion','/home/djmorrsee/Documents/school_compiler/Homework2/dj_lex.py',58),
  ('simple_statements -> simple_statement simple_statements','simple_statements',2,'p_statement_recursion','/home/djmorrsee/Documents/school_compiler/Homework2/dj_lex.py',59),
  ('simple_statement -> expression','simple_statement',1,'p_simple_statement','/home/djmorrsee/Documents/school_compiler/Homework2/dj_lex.py',63),
  ('simple_statement -> PRINT expression','simple_statement',2,'p_print_statement','/home/djmorrsee/Documents/school_compiler/Homework2/dj_lex.py',67),
  ('simple_statement -> NAME ASSIGNMENT expression','simple_statement',3,'p_assign_statement','/home/djmorrsee/Documents/school_compiler/Homework2/dj_lex.py',71),
  ('expression -> NAME','expression',1,'p_name_expression','/home/djmorrsee/Documents/school_compiler/Homework2/dj_lex.py',75),
  ('expression -> INT','expression',1,'p_integer_expression','/home/djmorrsee/Documents/school_compiler/Homework2/dj_lex.py',79),
  ('expression -> NEGATE expression','expression',2,'p_negate_expression','/home/djmorrsee/Documents/school_compiler/Homework2/dj_lex.py',83),
  ('expression -> expression PLUS expression','expression',3,'p_addition_expression','/home/djmorrsee/Documents/school_compiler/Homework2/dj_lex.py',87),
  ('expression -> INPUT LPARAN RPARAN','expression',3,'p_input_expression','/home/djmorrsee/Documents/school_compiler/Homework2/dj_lex.py',91),
  ('expression -> LPARAN expression RPARAN','expression',3,'p_paran_expression','/home/djmorrsee/Documents/school_compiler/Homework2/dj_lex.py',95),
]
